/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarTrabajadorRequestDto { 
    apellidos: string;
    cargoId: number;
    celular?: string;
    correo?: string;
    nombres: string;
}

