/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AvisoTiempoRealDto {
  tema?: AvisoTiempoRealDtoTemaEnum;
}
export enum AvisoTiempoRealDtoTemaEnum {
  COMANDAS = 'COMANDAS',
  COCINA = 'COCINA',
  REPARTO = 'REPARTO',
  MESAS = 'MESAS',
  RESERVAS = 'RESERVAS',
  CAJA = 'CAJA',
  STOCK = 'STOCK',
}
