/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BootstrapAdminRequestDto { 
    apellidos: string;
    celular: string;
    correo: string;
    dni: string;
    nombres: string;
    password: string;
    username: string;
}

