/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CargoResponseDto { 
    descripcion?: string;
    id?: number;
    nombre?: string;
    rolesNombres?: Array<string>;
}

