/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClienteRequestDto { 
    apellidos: string;
    celular?: string;
    correo?: string;
    direccionHabitual?: string;
    dni: string;
    nombres: string;
    tipoCliente?: string;
}

