/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClienteAnonimoRequestDto { 
    celular?: string;
    direccionHabitual?: string;
    nombreReferencia?: string;
}

