/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LineaKds } from './linea-kds';


export interface ComandaKdsDto { 
    correlativo?: string;
    estado?: ComandaKdsDtoEstadoEnum;
    flagCierrePlatillo?: boolean;
    fueraDeObjetivo?: boolean;
    lineas?: Array<LineaKds>;
    mesaNumero?: string;
    minutosEnCola?: number;
    ordenId?: string;
    recibida?: string;
    tipoOrden?: ComandaKdsDtoTipoOrdenEnum;
}
export enum ComandaKdsDtoEstadoEnum {
    ENCOLADO = 'ENCOLADO',
    EN_PREPARACION = 'EN_PREPARACION',
    EN_DESPACHO = 'EN_DESPACHO',
    ENTREGADO = 'ENTREGADO',
    PAGADO = 'PAGADO',
    CONCLUIDO = 'CONCLUIDO',
    CANCELADO = 'CANCELADO',
    FRAUDULENTO = 'FRAUDULENTO'
};
export enum ComandaKdsDtoTipoOrdenEnum {
    MESA = 'MESA',
    RETIRO_LOCAL = 'RETIRO_LOCAL',
    DELIVERY = 'DELIVERY'
};



