/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComplementoResponseDto { 
    activo?: boolean;
    id?: string;
    insumoAsociadoId?: string;
    insumoAsociadoNombre?: string;
    nombre?: string;
    precioAdicional?: number;
    tipoComplemento?: ComplementoResponseDtoTipoComplementoEnum;
}
export enum ComplementoResponseDtoTipoComplementoEnum {
    BEBIDA = 'BEBIDA',
    HELADO = 'HELADO',
    CERVEZA = 'CERVEZA',
    JUGO = 'JUGO',
    SALSAS = 'SALSAS',
    OTROS = 'OTROS'
};



