/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComplementoRequestDto { 
    activo?: boolean;
    insumoAsociadoId?: string;
    nombre: string;
    precioAdicional: number;
    tipoComplemento: ComplementoRequestDtoTipoComplementoEnum;
}
export enum ComplementoRequestDtoTipoComplementoEnum {
    BEBIDA = 'BEBIDA',
    HELADO = 'HELADO',
    CERVEZA = 'CERVEZA',
    JUGO = 'JUGO',
    SALSAS = 'SALSAS',
    OTROS = 'OTROS'
};



