/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Descuadre } from './descuadre';


export interface ConteoFisicoResponseDto { 
    descuadres?: Array<Descuadre>;
    insumosAjustados?: number;
    insumosContados?: number;
}

