/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemOrdenRequestDto } from './item-orden-request-dto';


export interface CrearOrdenRequestDto { 
    canalOrigen?: CrearOrdenRequestDtoCanalOrigenEnum;
    clienteId?: string;
    cuponCodigo?: string;
    direccionDelivery?: string;
    items: Array<ItemOrdenRequestDto>;
    mesaId?: string;
    promocionId?: string;
    tipoOrden: CrearOrdenRequestDtoTipoOrdenEnum;
    tipoPago: CrearOrdenRequestDtoTipoPagoEnum;
}
export enum CrearOrdenRequestDtoCanalOrigenEnum {
    POS = 'POS',
    WHATSAPP_BOT = 'WHATSAPP_BOT',
    WEB = 'WEB'
};
export enum CrearOrdenRequestDtoTipoOrdenEnum {
    MESA = 'MESA',
    RETIRO_LOCAL = 'RETIRO_LOCAL',
    DELIVERY = 'DELIVERY'
};
export enum CrearOrdenRequestDtoTipoPagoEnum {
    EFECTIVO = 'EFECTIVO',
    E_WALLET = 'E_WALLET',
    TARJETA = 'TARJETA'
};



