/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DesempenoDto {
  asistidos?: number;
  calificaciones?: number;
  cargo?: string;
  comandas?: number;
  desde?: string;
  hasta?: string;
  horasTrabajadas?: number;
  inasistencias?: number;
  minutosTarde?: number;
  nombre?: string;
  salidasSinMarcar?: number;
  satisfaccionAtencion?: number;
  tardanzas?: number;
  ticketPromedio?: number;
  trabajadorId?: string;
  turnos?: number;
  vendido?: number;
}
