/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemDisponibilidad } from './item-disponibilidad';


export interface DisponibilidadRequestDto { 
    items: Array<ItemDisponibilidad>;
}

