/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Faltante } from './faltante';


export interface DisponibilidadResponseDto { 
    disponible?: boolean;
    faltantes?: Array<Faltante>;
}

