/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VinculacionBotDto } from './vinculacion-bot-dto';
import { EstadoCanalBot } from './estado-canal-bot';

export interface EstadoBotsDto {
  canales?: Array<EstadoCanalBot>;
  disponible?: boolean;
  maxOpciones?: number;
  proveedorActivo?: string;
  proveedorPedido?: string;
  proveedoresDisponibles?: Array<string>;
  sesionesClienteAbiertas?: number;
  trabajadoresActivos?: number;
  trabajadoresVinculados?: number;
  vinculaciones?: Array<VinculacionBotDto>;
}
