/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NivelLealtadDto } from './nivel-lealtad-dto';

export interface FidelizacionDto {
  calificacionesFaltantes?: number;
  calificacionesRealizadas?: number;
  calificacionesRequeridas?: number;
  clienteId?: string;
  cuponesVigentes?: number;
  mensaje?: string;
  nivelActual?: NivelLealtadDto;
  nivelSiguiente?: NivelLealtadDto;
  puntosFidelidad?: number;
  puntosParaSiguiente?: number;
}
