/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplementoImportacionDto } from './complemento-importacion-dto';
import { SeccionImportacionDto } from './seccion-importacion-dto';

export interface ImportacionCartaDto {
  complementos?: Array<ComplementoImportacionDto>;
  secciones?: Array<SeccionImportacionDto>;
}
