/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InsumoResponseDto { 
    bajoMinimo?: boolean;
    id?: string;
    nombre?: string;
    stockActual?: number;
    stockMinimo?: number;
    tipoInsumo?: InsumoResponseDtoTipoInsumoEnum;
    unidadMedida?: string;
}
export enum InsumoResponseDtoTipoInsumoEnum {
    COCIDO = 'COCIDO',
    NO_COCIDO = 'NO_COCIDO'
};



