/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InsumoResponseDto {
  bajoMinimo?: boolean;
  cantidadPorVencer?: number;
  cantidadSinCosto?: number;
  cantidadVencida?: number;
  id?: string;
  nombre?: string;
  proximoVencimiento?: string;
  stockActual?: number;
  stockMinimo?: number;
  tipoInsumo?: InsumoResponseDtoTipoInsumoEnum;
  unidadMedida?: string;
  valorStock?: number;
}
export enum InsumoResponseDtoTipoInsumoEnum {
  COCIDO = 'COCIDO',
  NO_COCIDO = 'NO_COCIDO',
}
