/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InsumoValorizado } from './insumo-valorizado';

export interface InventarioValorizadoDto {
  insumos?: Array<InsumoValorizado>;
  insumosConStockSinCosto?: number;
  valorTotal?: number;
}
