/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplementoItemDto } from './complemento-item-dto';


export interface ItemOrdenRequestDto { 
    cantidad: number;
    complementos?: Array<ComplementoItemDto>;
    excepcionesNota?: string;
    platilloId: string;
}

