/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KpisCocinaDto { 
    comandasEnCola?: number;
    comandasEnPreparacion?: number;
    comandasFueraDeObjetivo?: number;
    minutosObjetivo?: number;
    minutosPromedioCocina?: number;
    minutosPromedioDespacho?: number;
    minutosPromedioRecepcion?: number;
    minutosPromedioTotal?: number;
}

