/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MesaResponseDto { 
    activa?: boolean;
    capacidad?: number;
    estado?: MesaResponseDtoEstadoEnum;
    id?: string;
    numero?: string;
    reservadaANombreDe?: string;
    reservadaPara?: string;
    zona?: string;
}
export enum MesaResponseDtoEstadoEnum {
    LIBRE = 'LIBRE',
    OCUPADA = 'OCUPADA',
    RESERVADA = 'RESERVADA',
    INHABILITADA = 'INHABILITADA'
};



