/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TurnoDto } from './turno-dto';

export interface MiAsistenciaDto {
  dentro?: boolean;
  entrada?: string;
  turnos?: Array<TurnoDto>;
}
