/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovimientosPorTipo { 
    cantidadMovimientos?: number;
    tipoControl?: MovimientosPorTipoTipoControlEnum;
    volumenTotal?: number;
}
export enum MovimientosPorTipoTipoControlEnum {
    ENTRADA_COMPRA = 'ENTRADA_COMPRA',
    TRANSFORMACION_COCIDO = 'TRANSFORMACION_COCIDO',
    SALIDA_VENTA = 'SALIDA_VENTA',
    MERMA_DESPERDICIO = 'MERMA_DESPERDICIO',
    AJUSTE_AUDITORIA = 'AJUSTE_AUDITORIA'
};



