/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NivelLealtadDto {
  readonly id?: string;
  nombre: string;
  porcentajeDescuento: number;
  puntosMinimos: number;
}
