/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplementoDetalleDto } from './complemento-detalle-dto';


export interface OrdenDetalleDto { 
    cantidad?: number;
    complementos?: Array<ComplementoDetalleDto>;
    excepcionesNota?: string;
    id?: string;
    montoSubtotal?: number;
    platilloId?: string;
    platilloNombre?: string;
    precioVentaProducto?: number;
}

