/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrdenDetalleDto } from './orden-detalle-dto';

export interface OrdenResponseDto {
  canalOrigen?: OrdenResponseDtoCanalOrigenEnum;
  clienteId?: string;
  clienteNombre?: string;
  codigoOtpEntrega?: string;
  cuponCodigo?: string;
  detalles?: Array<OrdenDetalleDto>;
  direccionDelivery?: string;
  editable?: boolean;
  estado?: OrdenResponseDtoEstadoEnum;
  flagCierreDespacho?: boolean;
  flagCierrePlatillo?: boolean;
  flagCierreRecepcion?: boolean;
  id?: string;
  mesaId?: string;
  mesaNumero?: string;
  montoBaseImponible?: number;
  montoDescuento?: number;
  montoIgv?: number;
  montoSubtotal?: number;
  montoTotal?: number;
  motivoCancelacion?: string;
  mozoId?: string;
  nivelLealtadNombre?: string;
  porcentajeIgv?: number;
  promocionNombre?: string;
  scoringRiesgoOrden?: number;
  tiempoCierreDespacho?: string;
  tiempoCierrePlatillo?: string;
  tiempoCierreRecepcion?: string;
  tiempoEstimadoCocinaMinutos?: number;
  tiempoFinGlobal?: string;
  tiempoInicioCocina?: string;
  tiempoInicioGlobal?: string;
  tipoOrden?: OrdenResponseDtoTipoOrdenEnum;
  tipoPago?: OrdenResponseDtoTipoPagoEnum;
  transicionesPermitidas?: Array<OrdenResponseDtoTransicionesPermitidasEnum>;
}
export enum OrdenResponseDtoCanalOrigenEnum {
  POS = 'POS',
  WHATSAPP_BOT = 'WHATSAPP_BOT',
  DISCORD_BOT = 'DISCORD_BOT',
  WEB = 'WEB',
}
export enum OrdenResponseDtoEstadoEnum {
  ENCOLADO = 'ENCOLADO',
  EN_PREPARACION = 'EN_PREPARACION',
  EN_DESPACHO = 'EN_DESPACHO',
  ENTREGADO = 'ENTREGADO',
  PAGADO = 'PAGADO',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO',
  FRAUDULENTO = 'FRAUDULENTO',
}
export enum OrdenResponseDtoTipoOrdenEnum {
  MESA = 'MESA',
  RETIRO_LOCAL = 'RETIRO_LOCAL',
  DELIVERY = 'DELIVERY',
}
export enum OrdenResponseDtoTipoPagoEnum {
  EFECTIVO = 'EFECTIVO',
  E_WALLET = 'E_WALLET',
  TARJETA = 'TARJETA',
}
export enum OrdenResponseDtoTransicionesPermitidasEnum {
  ENCOLADO = 'ENCOLADO',
  EN_PREPARACION = 'EN_PREPARACION',
  EN_DESPACHO = 'EN_DESPACHO',
  ENTREGADO = 'ENTREGADO',
  PAGADO = 'PAGADO',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO',
  FRAUDULENTO = 'FRAUDULENTO',
}
