/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrabajadorResponseDto } from './trabajador-response-dto';


export interface PageResponseDtoTrabajadorResponseDto { 
    contenido?: Array<TrabajadorResponseDto>;
    pagina?: number;
    primera?: boolean;
    tamano?: number;
    totalElementos?: number;
    totalPaginas?: number;
    ultima?: boolean;
}

