/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrdenResumenDto } from './orden-resumen-dto';


export interface PageResponseDtoOrdenResumenDto { 
    contenido?: Array<OrdenResumenDto>;
    pagina?: number;
    primera?: boolean;
    tamano?: number;
    totalElementos?: number;
    totalPaginas?: number;
    ultima?: boolean;
}

