/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PagoResponseDto { 
    esFraudulento?: boolean;
    estado?: PagoResponseDtoEstadoEnum;
    fecha?: string;
    id?: string;
    monto?: number;
    montoEntregado?: number;
    observacion?: string;
    ordenId?: string;
    referencia?: string;
    registradoPor?: string;
    tipoPago?: PagoResponseDtoTipoPagoEnum;
    vuelto?: number;
}
export enum PagoResponseDtoEstadoEnum {
    PENDIENTE = 'PENDIENTE',
    CONFIRMADO = 'CONFIRMADO',
    RECHAZADO = 'RECHAZADO',
    FRAUDULENTO = 'FRAUDULENTO'
};
export enum PagoResponseDtoTipoPagoEnum {
    EFECTIVO = 'EFECTIVO',
    E_WALLET = 'E_WALLET',
    TARJETA = 'TARJETA'
};



