/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PosicionMesa } from './posicion-mesa';

export interface PlanoRequestDto {
  mesas: Array<PosicionMesa>;
}
