/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PlatilloLeidoDto {
  descripcion?: string;
  dudoso?: boolean;
  nombre?: string;
  precio?: number;
  /**
   * Recorte de la foto de donde salio, como data URL JPEG. Solo en las filas dudosas.
   */
  recorte?: string;
  vegetariano?: boolean;
}
