/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlatilloDisponibleDto { 
    categoriaId?: number;
    categoriaNombre?: string;
    descripcion?: string;
    disponible?: boolean;
    id?: string;
    insumosFaltantes?: Array<string>;
    nombre?: string;
    porcionesPosibles?: number;
    precioVentaBase?: number;
}

