/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecetaItemDto } from './receta-item-dto';


export interface PlatilloResponseDto { 
    activo?: boolean;
    categoriaId?: number;
    categoriaNombre?: string;
    descripcion?: string;
    id?: string;
    nombre?: string;
    precioVentaBase?: number;
    receta?: Array<RecetaItemDto>;
}

