/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PorMetodo { 
    cantidad?: number;
    tipoPago?: PorMetodoTipoPagoEnum;
    total?: number;
}
export enum PorMetodoTipoPagoEnum {
    EFECTIVO = 'EFECTIVO',
    E_WALLET = 'E_WALLET',
    TARJETA = 'TARJETA'
};



