/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PorEstado {
  comandas?: number;
  estado?: PorEstadoEstadoEnum;
  total?: number;
}
export enum PorEstadoEstadoEnum {
  ENCOLADO = 'ENCOLADO',
  EN_PREPARACION = 'EN_PREPARACION',
  EN_DESPACHO = 'EN_DESPACHO',
  ENTREGADO = 'ENTREGADO',
  PAGADO = 'PAGADO',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO',
  FRAUDULENTO = 'FRAUDULENTO',
}
