/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PorCanal { 
    canal?: PorCanalCanalEnum;
    cantidadComandas?: number;
    total?: number;
}
export enum PorCanalCanalEnum {
    POS = 'POS',
    WHATSAPP_BOT = 'WHATSAPP_BOT',
    WEB = 'WEB'
};



