/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PosicionMesa {
  alto: number;
  ancho: number;
  columna: number;
  fila: number;
  forma?: PosicionMesaFormaEnum;
  id: string;
}
export enum PosicionMesaFormaEnum {
  CUADRADA = 'CUADRADA',
  REDONDA = 'REDONDA',
}
