/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PromocionRequestDto { 
    activa?: boolean;
    descripcion?: string;
    fechaFin: string;
    fechaInicio: string;
    insumoExtraId?: string;
    montoDescuento?: number;
    nombre: string;
    porcentajeDescuento?: number;
    requiereInsumoExtra?: boolean;
}

