/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProveedorDto {
  readonly activo?: boolean;
  contacto?: string;
  correo?: string;
  readonly id?: string;
  nombre: string;
  ruc?: string;
  telefono?: string;
}
