/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ReservaRequestDto {
  celular?: string;
  duracionMinutos?: number;
  inicio: string;
  mesaId: string;
  nombre: string;
  nota?: string;
  personas: number;
}
