/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ResultadoImportacionCartaDto {
  complementosActualizados?: number;
  complementosCreados?: number;
  platillosActualizados?: number;
  platillosCreados?: number;
  platillosSinCambios?: number;
  seccionesCreadas?: number;
}
