/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlatilloLeidoDto } from './platillo-leido-dto';

export interface SeccionLeidaDto {
  nombre?: string;
  platillos?: Array<PlatilloLeidoDto>;
}
