/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlatilloImportacionDto } from './platillo-importacion-dto';

export interface SeccionImportacionDto {
  categoriaId?: number;
  nombreNueva?: string;
  platillos?: Array<PlatilloImportacionDto>;
}
