/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Punto } from './punto';

export interface SerieVentasDto {
  desde?: string;
  granularidad?: SerieVentasDtoGranularidadEnum;
  hasta?: string;
  puntos?: Array<Punto>;
}
export enum SerieVentasDtoGranularidadEnum {
  HORA = 'HORA',
  DIA = 'DIA',
}
