/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LineaTicket } from './linea-ticket';


export interface TicketCocinaDto { 
    clienteNombre?: string;
    correlativo?: string;
    emitido?: string;
    lineas?: Array<LineaTicket>;
    mesaNumero?: string;
    ordenId?: string;
    tipoOrden?: TicketCocinaDtoTipoOrdenEnum;
}
export enum TicketCocinaDtoTipoOrdenEnum {
    MESA = 'MESA',
    RETIRO_LOCAL = 'RETIRO_LOCAL',
    DELIVERY = 'DELIVERY'
};



