/**
 * Backend Logistica - Chaquena
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehiculoResponseDto { 
    activo?: boolean;
    id?: string;
    marcaModelo?: string;
    placa?: string;
    tipoVehiculo?: VehiculoResponseDtoTipoVehiculoEnum;
    transportistaId?: string;
}
export enum VehiculoResponseDtoTipoVehiculoEnum {
    MOTO = 'MOTO',
    TAXI_AUTO = 'TAXI_AUTO',
    BICICLETA = 'BICICLETA'
};



