/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VentasPorMetodoPagoDto {
  metodo?: VentasPorMetodoPagoDtoMetodoEnum;
  pagos?: number;
  total?: number;
}
export enum VentasPorMetodoPagoDtoMetodoEnum {
  EFECTIVO = 'EFECTIVO',
  E_WALLET = 'E_WALLET',
  TARJETA = 'TARJETA',
}
