export * from './autenticacion.api';
import { AutenticacionApi } from './autenticacion.api';
export * from './caja-arqueo-y-fraude.api';
import { CajaArqueoYFraudeApi } from './caja-arqueo-y-fraude.api';
export * from './caja-pagos.api';
import { CajaPagosApi } from './caja-pagos.api';
export * from './cargos.api';
import { CargosApi } from './cargos.api';
export * from './catalogo-categorias.api';
import { CatalogoCategoriasApi } from './catalogo-categorias.api';
export * from './catalogo-complementos.api';
import { CatalogoComplementosApi } from './catalogo-complementos.api';
export * from './catalogo-platillos.api';
import { CatalogoPlatillosApi } from './catalogo-platillos.api';
export * from './catalogo-promociones.api';
import { CatalogoPromocionesApi } from './catalogo-promociones.api';
export * from './clientes.api';
import { ClientesApi } from './clientes.api';
export * from './clientes-empresas.api';
import { ClientesEmpresasApi } from './clientes-empresas.api';
export * from './cocina-kds.api';
import { CocinaKDSApi } from './cocina-kds.api';
export * from './comandas.api';
import { ComandasApi } from './comandas.api';
export * from './despacho-reparto.api';
import { DespachoRepartoApi } from './despacho-reparto.api';
export * from './despacho-transportistas.api';
import { DespachoTransportistasApi } from './despacho-transportistas.api';
export * from './feedback-y-fidelizacion.api';
import { FeedbackYFidelizacionApi } from './feedback-y-fidelizacion.api';
export * from './inventario-insumos.api';
import { InventarioInsumosApi } from './inventario-insumos.api';
export * from './inventario-movimientos.api';
import { InventarioMovimientosApi } from './inventario-movimientos.api';
export * from './outbox.api';
import { OutboxApi } from './outbox.api';
export * from './reportes.api';
import { ReportesApi } from './reportes.api';
export * from './salon-mesas.api';
import { SalonMesasApi } from './salon-mesas.api';
export * from './trabajadores.api';
import { TrabajadoresApi } from './trabajadores.api';
export const APIS = [AutenticacionApi, CajaArqueoYFraudeApi, CajaPagosApi, CargosApi, CatalogoCategoriasApi, CatalogoComplementosApi, CatalogoPlatillosApi, CatalogoPromocionesApi, ClientesApi, ClientesEmpresasApi, CocinaKDSApi, ComandasApi, DespachoRepartoApi, DespachoTransportistasApi, FeedbackYFidelizacionApi, InventarioInsumosApi, InventarioMovimientosApi, OutboxApi, ReportesApi, SalonMesasApi, TrabajadoresApi];
