/**
 * Backend Logistica - Chaquena
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpContext,
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

export interface ExportarAsistenciaRequestParams {
  formato?: 'PDF' | 'XLSX';
  desde?: string;
  hasta?: string;
}

export interface ExportarInventarioRequestParams {
  formato?: 'PDF' | 'XLSX';
}

export interface ExportarProductosRequestParams {
  formato?: 'PDF' | 'XLSX';
  desde?: string;
  hasta?: string;
}

export interface ExportarVentasRequestParams {
  formato?: 'PDF' | 'XLSX';
  desde?: string;
  hasta?: string;
}

@Injectable({
  providedIn: 'root',
})
export class ReportesExportarApi extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration,
  ) {
    super(basePath, configuration);
  }

  /**
   * Asistencia por dia y resumen por persona
   * Sin rango, los ultimos siete dias. Un rango al reves se da vuelta; hasta un ano.
   * @endpoint get /api/v1/reportes/asistencia/exportar
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public exportarAsistencia(
    requestParameters?: ExportarAsistenciaRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<Blob>;
  public exportarAsistencia(
    requestParameters?: ExportarAsistenciaRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<Blob>>;
  public exportarAsistencia(
    requestParameters?: ExportarAsistenciaRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<Blob>>;
  public exportarAsistencia(
    requestParameters?: ExportarAsistenciaRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    const formato = requestParameters?.formato;
    const desde = requestParameters?.desde;
    const hasta = requestParameters?.hasta;

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'formato',
      <any>formato,
      QueryParamStyle.Form,
      true,
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'desde',
      <any>desde,
      QueryParamStyle.Form,
      true,
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'hasta',
      <any>hasta,
      QueryParamStyle.Form,
      true,
    );

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'bearerAuth',
      'Authorization',
      localVarHeaders,
      'Bearer ',
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let localVarPath = `/api/v1/reportes/asistencia/exportar`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters.toHttpParams(),
      responseType: 'blob',
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
      reportProgress: reportProgress,
    });
  }

  /**
   * El almacen en este momento: stock, minimo, vencimientos y valor
   * @endpoint get /api/v1/reportes/inventario/exportar
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public exportarInventario(
    requestParameters?: ExportarInventarioRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<Blob>;
  public exportarInventario(
    requestParameters?: ExportarInventarioRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<Blob>>;
  public exportarInventario(
    requestParameters?: ExportarInventarioRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<Blob>>;
  public exportarInventario(
    requestParameters?: ExportarInventarioRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    const formato = requestParameters?.formato;

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'formato',
      <any>formato,
      QueryParamStyle.Form,
      true,
    );

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'bearerAuth',
      'Authorization',
      localVarHeaders,
      'Bearer ',
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let localVarPath = `/api/v1/reportes/inventario/exportar`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters.toHttpParams(),
      responseType: 'blob',
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
      reportProgress: reportProgress,
    });
  }

  /**
   * Todos los platillos vendidos en el rango, del mas vendido al menos
   * @endpoint get /api/v1/reportes/productos/exportar
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public exportarProductos(
    requestParameters?: ExportarProductosRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<Blob>;
  public exportarProductos(
    requestParameters?: ExportarProductosRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<Blob>>;
  public exportarProductos(
    requestParameters?: ExportarProductosRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<Blob>>;
  public exportarProductos(
    requestParameters?: ExportarProductosRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    const formato = requestParameters?.formato;
    const desde = requestParameters?.desde;
    const hasta = requestParameters?.hasta;

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'formato',
      <any>formato,
      QueryParamStyle.Form,
      true,
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'desde',
      <any>desde,
      QueryParamStyle.Form,
      true,
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'hasta',
      <any>hasta,
      QueryParamStyle.Form,
      true,
    );

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'bearerAuth',
      'Authorization',
      localVarHeaders,
      'Bearer ',
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let localVarPath = `/api/v1/reportes/productos/exportar`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters.toHttpParams(),
      responseType: 'blob',
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
      reportProgress: reportProgress,
    });
  }

  /**
   * Ventas del rango: resumen, canal, metodo de pago, dia y mozo
   * @endpoint get /api/v1/reportes/ventas/exportar
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public exportarVentas(
    requestParameters?: ExportarVentasRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<Blob>;
  public exportarVentas(
    requestParameters?: ExportarVentasRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<Blob>>;
  public exportarVentas(
    requestParameters?: ExportarVentasRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<Blob>>;
  public exportarVentas(
    requestParameters?: ExportarVentasRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?:
        'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    const formato = requestParameters?.formato;
    const desde = requestParameters?.desde;
    const hasta = requestParameters?.hasta;

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'formato',
      <any>formato,
      QueryParamStyle.Form,
      true,
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'desde',
      <any>desde,
      QueryParamStyle.Form,
      true,
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'hasta',
      <any>hasta,
      QueryParamStyle.Form,
      true,
    );

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'bearerAuth',
      'Authorization',
      localVarHeaders,
      'Bearer ',
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept([
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let localVarPath = `/api/v1/reportes/ventas/exportar`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters.toHttpParams(),
      responseType: 'blob',
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
      reportProgress: reportProgress,
    });
  }
}
