--
-- PostgreSQL database dump
--

\restrict 71PJlu1V74g1RoT8Ig5kMfCfedvgXAjleOQJpzOmxERFZk3NDAnLhuxBQ04ChdI

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: calificaciones_feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calificaciones_feedback (
    id bigint NOT NULL,
    comentario text,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    puntaje_atencion integer NOT NULL,
    puntaje_comida integer NOT NULL,
    puntaje_lugar integer NOT NULL,
    cliente_id uuid,
    orden_id uuid NOT NULL
);


--
-- Name: calificaciones_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.calificaciones_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calificaciones_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cargo_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cargo_roles (
    id integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    cargo_id integer NOT NULL,
    rol_id integer NOT NULL
);


--
-- Name: cargo_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cargo_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cargo_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cargos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cargos (
    id integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    descripcion character varying(255),
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: cargos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cargos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cargos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias_platillo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categorias_platillo (
    id integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    descripcion text,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: categorias_platillo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categorias_platillo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_platillo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente_empresas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente_empresas (
    id integer NOT NULL,
    cargo_en_empresa character varying(100),
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    empresa_id uuid NOT NULL,
    persona_id uuid NOT NULL
);


--
-- Name: cliente_empresas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cliente_empresas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_empresas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    bloqueado_por_fraude boolean DEFAULT false NOT NULL,
    direccion_habitual text,
    puntos_fidelidad integer DEFAULT 0 NOT NULL,
    score_fraude integer DEFAULT 0 NOT NULL,
    tipo_cliente character varying(50),
    persona_id uuid NOT NULL
);


--
-- Name: complementos_platillo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.complementos_platillo (
    id uuid NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    nombre character varying(100) NOT NULL,
    precio_adicional numeric(10,2) NOT NULL,
    tipo_complemento character varying(20) NOT NULL,
    insumo_asociado_id uuid,
    CONSTRAINT complementos_platillo_tipo_complemento_check CHECK (((tipo_complemento)::text = ANY ((ARRAY['BEBIDA'::character varying, 'HELADO'::character varying, 'CERVEZA'::character varying, 'JUGO'::character varying, 'SALSAS'::character varying, 'OTROS'::character varying])::text[])))
);


--
-- Name: configuracion_local; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion_local (
    id integer NOT NULL,
    calificaciones_para_cupon integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    dias_vigencia_cupon integer DEFAULT 30 NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    minutos_objetivo_cocina integer DEFAULT 20 NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    porcentaje_descuento_cupon numeric(5,2) DEFAULT 10.00 NOT NULL
);


--
-- Name: controles_insumo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.controles_insumo (
    id uuid NOT NULL,
    cantidad numeric(12,3) NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    motivo_observacion text,
    stock_anterior numeric(12,3) NOT NULL,
    stock_nuevo numeric(12,3) NOT NULL,
    tipo_control character varying(30) NOT NULL,
    trabajador_id uuid NOT NULL,
    insumo_id uuid NOT NULL,
    CONSTRAINT controles_insumo_tipo_control_check CHECK (((tipo_control)::text = ANY ((ARRAY['ENTRADA_COMPRA'::character varying, 'TRANSFORMACION_COCIDO'::character varying, 'SALIDA_VENTA'::character varying, 'MERMA_DESPERDICIO'::character varying, 'AJUSTE_AUDITORIA'::character varying])::text[])))
);


--
-- Name: cupones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cupones (
    id uuid NOT NULL,
    codigo character varying(20) NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    descripcion character varying(200),
    estado character varying(20) NOT NULL,
    fecha_canje timestamp(6) with time zone,
    fecha_emision timestamp(6) with time zone NOT NULL,
    fecha_vencimiento timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    monto_descuento numeric(10,2) DEFAULT 0 NOT NULL,
    orden_canje_id uuid,
    porcentaje_descuento numeric(5,2) DEFAULT 0 NOT NULL,
    cliente_id uuid NOT NULL,
    CONSTRAINT cupones_estado_check CHECK (((estado)::text = ANY ((ARRAY['VIGENTE'::character varying, 'CANJEADO'::character varying, 'VENCIDO'::character varying, 'ANULADO'::character varying])::text[])))
);


--
-- Name: empresas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.empresas (
    id uuid NOT NULL,
    celular character varying(20),
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    direccion_fiscal text,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    razon_social character varying(200) NOT NULL,
    ruc character varying(11) NOT NULL
);


--
-- Name: insumos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.insumos (
    id uuid NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    nombre character varying(100) NOT NULL,
    stock_actual numeric(12,3) NOT NULL,
    stock_minimo numeric(12,3) NOT NULL,
    tipo_insumo character varying(20) NOT NULL,
    unidad_medida character varying(20) NOT NULL,
    CONSTRAINT insumos_tipo_insumo_check CHECK (((tipo_insumo)::text = ANY ((ARRAY['COCIDO'::character varying, 'NO_COCIDO'::character varying])::text[])))
);


--
-- Name: insumos_platillo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.insumos_platillo (
    id integer NOT NULL,
    cantidad_requerida numeric(12,3) NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    insumo_id uuid NOT NULL,
    platillo_id uuid NOT NULL
);


--
-- Name: insumos_platillo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.insumos_platillo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insumos_platillo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mesas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mesas (
    id uuid NOT NULL,
    activa boolean DEFAULT true NOT NULL,
    capacidad integer,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    estado character varying(20) NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    numero character varying(10) NOT NULL,
    reservada_a_nombre_de character varying(120),
    reservada_para timestamp(6) with time zone,
    zona character varying(50),
    CONSTRAINT mesas_estado_check CHECK (((estado)::text = ANY ((ARRAY['LIBRE'::character varying, 'OCUPADA'::character varying, 'RESERVADA'::character varying, 'INHABILITADA'::character varying])::text[])))
);


--
-- Name: orden_delivery_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orden_delivery_info (
    id bigint NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    hora_despacho timestamp(6) with time zone,
    hora_entrega timestamp(6) with time zone,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    otp_verificado boolean DEFAULT false NOT NULL,
    tiempo_estimado_minutos integer,
    orden_id uuid NOT NULL,
    transportista_id uuid,
    vehiculo_id uuid
);


--
-- Name: orden_delivery_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orden_delivery_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orden_delivery_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orden_detalle_complementos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orden_detalle_complementos (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    precio_venta_complemento numeric(10,2) NOT NULL,
    complemento_id uuid NOT NULL,
    orden_detalle_id uuid NOT NULL
);


--
-- Name: orden_detalle_complementos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orden_detalle_complementos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orden_detalle_complementos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orden_detalles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orden_detalles (
    id uuid NOT NULL,
    cantidad integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    excepciones_nota text,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    monto_subtotal numeric(10,2) NOT NULL,
    precio_venta_producto numeric(10,2) NOT NULL,
    orden_id uuid NOT NULL,
    platillo_id uuid NOT NULL
);


--
-- Name: ordenes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ordenes (
    id uuid NOT NULL,
    canal_origen character varying(20) NOT NULL,
    codigo_otp_entrega character varying(6),
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    direccion_delivery text,
    estado character varying(20) NOT NULL,
    flag_cierre_despacho boolean DEFAULT false NOT NULL,
    flag_cierre_platillo boolean DEFAULT false NOT NULL,
    flag_cierre_recepcion boolean DEFAULT false NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    mesa_numero character varying(10),
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    monto_descuento numeric(10,2) DEFAULT 0 NOT NULL,
    monto_subtotal numeric(10,2) NOT NULL,
    monto_total numeric(10,2) NOT NULL,
    mozo_id uuid,
    scoring_riesgo_orden integer DEFAULT 0 NOT NULL,
    tiempo_fin_global timestamp(6) with time zone,
    tiempo_inicio_global timestamp(6) with time zone,
    tipo_orden character varying(20) NOT NULL,
    tipo_pago character varying(20) NOT NULL,
    cliente_id uuid,
    cupon_codigo character varying(20),
    motivo_cancelacion text,
    tiempo_cierre_despacho timestamp(6) with time zone,
    tiempo_cierre_platillo timestamp(6) with time zone,
    tiempo_cierre_recepcion timestamp(6) with time zone,
    tiempo_inicio_cocina timestamp(6) with time zone,
    mesa_id uuid,
    promocion_id uuid,
    tiempo_estimado_cocina_minutos integer,
    CONSTRAINT ordenes_canal_origen_check CHECK (((canal_origen)::text = ANY ((ARRAY['POS'::character varying, 'WHATSAPP_BOT'::character varying, 'WEB'::character varying])::text[]))),
    CONSTRAINT ordenes_estado_check CHECK (((estado)::text = ANY ((ARRAY['ENCOLADO'::character varying, 'EN_PREPARACION'::character varying, 'EN_DESPACHO'::character varying, 'ENTREGADO'::character varying, 'PAGADO'::character varying, 'CONCLUIDO'::character varying, 'CANCELADO'::character varying, 'FRAUDULENTO'::character varying])::text[]))),
    CONSTRAINT ordenes_tipo_orden_check CHECK (((tipo_orden)::text = ANY ((ARRAY['MESA'::character varying, 'RETIRO_LOCAL'::character varying, 'DELIVERY'::character varying])::text[]))),
    CONSTRAINT ordenes_tipo_pago_check CHECK (((tipo_pago)::text = ANY ((ARRAY['EFECTIVO'::character varying, 'E_WALLET'::character varying, 'TARJETA'::character varying])::text[])))
);


--
-- Name: outbox_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_events (
    id uuid NOT NULL,
    aggregate_id character varying(100) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    error_message text,
    event_type character varying(100) NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    next_retry_at timestamp(6) with time zone,
    payload jsonb NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT outbox_events_status_check CHECK (((status)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PROCESADO'::character varying, 'ERROR'::character varying, 'DEAD_LETTER'::character varying])::text[])))
);


--
-- Name: pagos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pagos (
    id uuid NOT NULL,
    cajero_id uuid,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    es_fraudulento boolean DEFAULT false NOT NULL,
    estado character varying(20) NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    monto numeric(10,2) NOT NULL,
    monto_entregado numeric(10,2) NOT NULL,
    observacion text,
    referencia character varying(120),
    tipo_pago character varying(20) NOT NULL,
    vuelto numeric(10,2) DEFAULT 0 NOT NULL,
    orden_id uuid NOT NULL,
    CONSTRAINT pagos_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'CONFIRMADO'::character varying, 'RECHAZADO'::character varying, 'FRAUDULENTO'::character varying])::text[]))),
    CONSTRAINT pagos_tipo_pago_check CHECK (((tipo_pago)::text = ANY ((ARRAY['EFECTIVO'::character varying, 'E_WALLET'::character varying, 'TARJETA'::character varying])::text[])))
);


--
-- Name: permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permisos (
    id integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    modulo character varying(50) NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: permisos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permisos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permisos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas (
    id uuid NOT NULL,
    apellidos character varying(100) NOT NULL,
    celular character varying(20),
    correo character varying(100),
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    dni character varying(15) NOT NULL,
    fecha_ultimo_cambio_correo timestamp(6) with time zone,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    nombres character varying(100) NOT NULL,
    discord_user_id character varying(32)
);


--
-- Name: platillos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platillos (
    id uuid NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    descripcion text,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    nombre character varying(150) NOT NULL,
    precio_venta_base numeric(10,2) NOT NULL,
    categoria_id integer NOT NULL
);


--
-- Name: promociones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promociones (
    id uuid NOT NULL,
    activa boolean DEFAULT true NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    descripcion text,
    fecha_fin timestamp(6) with time zone NOT NULL,
    fecha_inicio timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    monto_descuento numeric(10,2) DEFAULT 0 NOT NULL,
    nombre character varying(100) NOT NULL,
    porcentaje_descuento numeric(5,2) DEFAULT 0 NOT NULL,
    requiere_insumo_extra boolean DEFAULT false NOT NULL,
    insumo_extra_id uuid
);


--
-- Name: rol_permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rol_permisos (
    permiso_id integer NOT NULL,
    rol_id integer NOT NULL,
    id integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL
);


--
-- Name: rol_permisos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rol_permisos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_permisos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    descripcion character varying(255),
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    nombre character varying(50) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sesiones_bot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sesiones_bot (
    id uuid NOT NULL,
    canal character varying(10) NOT NULL,
    carrito_json jsonb NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    expira_en timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    paso_actual character varying(50) NOT NULL,
    remitente_id character varying(64) NOT NULL,
    cliente_id uuid,
    CONSTRAINT sesiones_bot_canal_check CHECK (((canal)::text = ANY ((ARRAY['IN'::character varying, 'OUT'::character varying])::text[])))
);


--
-- Name: trabajadores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trabajadores (
    persona_id uuid NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    cargo_id integer NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(50) NOT NULL
);


--
-- Name: transportistas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transportistas (
    activo boolean DEFAULT true NOT NULL,
    empresa_transporte character varying(100) NOT NULL,
    persona_id uuid NOT NULL
);


--
-- Name: vehiculos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehiculos (
    id uuid NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    marca_modelo character varying(100),
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    placa character varying(15) NOT NULL,
    tipo_vehiculo character varying(20) NOT NULL,
    transportista_id uuid NOT NULL,
    CONSTRAINT vehiculos_tipo_vehiculo_check CHECK (((tipo_vehiculo)::text = ANY ((ARRAY['MOTO'::character varying, 'TAXI_AUTO'::character varying, 'BICICLETA'::character varying])::text[])))
);


--
-- Name: whatsapp_sesiones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.whatsapp_sesiones (
    id uuid NOT NULL,
    carrito_json jsonb NOT NULL,
    created_by character varying(50) NOT NULL,
    date_created timestamp(6) with time zone NOT NULL,
    expira_en timestamp(6) with time zone NOT NULL,
    last_date_modified timestamp(6) with time zone DEFAULT now() NOT NULL,
    modified_by character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,
    paso_actual character varying(50) NOT NULL,
    telefono_whatsapp character varying(20) NOT NULL,
    cliente_id uuid
);


--
-- Name: calificaciones_feedback calificaciones_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificaciones_feedback
    ADD CONSTRAINT calificaciones_feedback_pkey PRIMARY KEY (id);


--
-- Name: cargo_roles cargo_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cargo_roles
    ADD CONSTRAINT cargo_roles_pkey PRIMARY KEY (id);


--
-- Name: cargos cargos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cargos
    ADD CONSTRAINT cargos_pkey PRIMARY KEY (id);


--
-- Name: categorias_platillo categorias_platillo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias_platillo
    ADD CONSTRAINT categorias_platillo_pkey PRIMARY KEY (id);


--
-- Name: cliente_empresas cliente_empresas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente_empresas
    ADD CONSTRAINT cliente_empresas_pkey PRIMARY KEY (id);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (persona_id);


--
-- Name: complementos_platillo complementos_platillo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complementos_platillo
    ADD CONSTRAINT complementos_platillo_pkey PRIMARY KEY (id);


--
-- Name: configuracion_local configuracion_local_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_local
    ADD CONSTRAINT configuracion_local_pkey PRIMARY KEY (id);


--
-- Name: controles_insumo controles_insumo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.controles_insumo
    ADD CONSTRAINT controles_insumo_pkey PRIMARY KEY (id);


--
-- Name: cupones cupones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupones
    ADD CONSTRAINT cupones_pkey PRIMARY KEY (id);


--
-- Name: empresas empresas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_pkey PRIMARY KEY (id);


--
-- Name: insumos insumos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumos
    ADD CONSTRAINT insumos_pkey PRIMARY KEY (id);


--
-- Name: insumos_platillo insumos_platillo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumos_platillo
    ADD CONSTRAINT insumos_platillo_pkey PRIMARY KEY (id);


--
-- Name: mesas mesas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mesas
    ADD CONSTRAINT mesas_pkey PRIMARY KEY (id);


--
-- Name: orden_delivery_info orden_delivery_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_delivery_info
    ADD CONSTRAINT orden_delivery_info_pkey PRIMARY KEY (id);


--
-- Name: orden_detalle_complementos orden_detalle_complementos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_detalle_complementos
    ADD CONSTRAINT orden_detalle_complementos_pkey PRIMARY KEY (id);


--
-- Name: orden_detalles orden_detalles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_detalles
    ADD CONSTRAINT orden_detalles_pkey PRIMARY KEY (id);


--
-- Name: ordenes ordenes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordenes
    ADD CONSTRAINT ordenes_pkey PRIMARY KEY (id);


--
-- Name: outbox_events outbox_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);


--
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id);


--
-- Name: permisos permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_pkey PRIMARY KEY (id);


--
-- Name: personas personas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas
    ADD CONSTRAINT personas_pkey PRIMARY KEY (id);


--
-- Name: platillos platillos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platillos
    ADD CONSTRAINT platillos_pkey PRIMARY KEY (id);


--
-- Name: promociones promociones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promociones
    ADD CONSTRAINT promociones_pkey PRIMARY KEY (id);


--
-- Name: rol_permisos rol_permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol_permisos
    ADD CONSTRAINT rol_permisos_pkey PRIMARY KEY (permiso_id, rol_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sesiones_bot sesiones_bot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesiones_bot
    ADD CONSTRAINT sesiones_bot_pkey PRIMARY KEY (id);


--
-- Name: trabajadores trabajadores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trabajadores
    ADD CONSTRAINT trabajadores_pkey PRIMARY KEY (persona_id);


--
-- Name: transportistas transportistas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transportistas
    ADD CONSTRAINT transportistas_pkey PRIMARY KEY (persona_id);


--
-- Name: personas uk1f3wqd14lwfifrd1308leu73o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas
    ADD CONSTRAINT uk1f3wqd14lwfifrd1308leu73o UNIQUE (correo);


--
-- Name: trabajadores uk40fk2b36s84lu990wgpl9a5hv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trabajadores
    ADD CONSTRAINT uk40fk2b36s84lu990wgpl9a5hv UNIQUE (username);


--
-- Name: personas uk60805t6wtrmol5sdqy36buyry; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas
    ADD CONSTRAINT uk60805t6wtrmol5sdqy36buyry UNIQUE (celular);


--
-- Name: whatsapp_sesiones uk851u5s4sq0tq9umuopi8mmsnb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.whatsapp_sesiones
    ADD CONSTRAINT uk851u5s4sq0tq9umuopi8mmsnb UNIQUE (telefono_whatsapp);


--
-- Name: cargos uk8pv3xgu821yh2yunllxo16nh5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cargos
    ADD CONSTRAINT uk8pv3xgu821yh2yunllxo16nh5 UNIQUE (nombre);


--
-- Name: sesiones_bot uk_sesion_bot_canal_remitente; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesiones_bot
    ADD CONSTRAINT uk_sesion_bot_canal_remitente UNIQUE (canal, remitente_id);


--
-- Name: vehiculos uka8w6omovfa10q8eyjalqas391; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehiculos
    ADD CONSTRAINT uka8w6omovfa10q8eyjalqas391 UNIQUE (placa);


--
-- Name: personas ukc9jn05t09024ovdivc5kfg8dm; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas
    ADD CONSTRAINT ukc9jn05t09024ovdivc5kfg8dm UNIQUE (discord_user_id);


--
-- Name: empresas ukd6avi1g5t06l7qo67kj8ty2j2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT ukd6avi1g5t06l7qo67kj8ty2j2 UNIQUE (ruc);


--
-- Name: calificaciones_feedback ukhc9rbjp5bqeg7yk50vm0bn8d4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificaciones_feedback
    ADD CONSTRAINT ukhc9rbjp5bqeg7yk50vm0bn8d4 UNIQUE (orden_id);


--
-- Name: mesas ukj0e0hutvqcecq56ogqll8feqw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mesas
    ADD CONSTRAINT ukj0e0hutvqcecq56ogqll8feqw UNIQUE (numero);


--
-- Name: roles ukldv0v52e0udsh2h1rs0r0gw1n; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukldv0v52e0udsh2h1rs0r0gw1n UNIQUE (nombre);


--
-- Name: permisos ukmd9j2tw7h6dxprrypo0itpnyp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT ukmd9j2tw7h6dxprrypo0itpnyp UNIQUE (nombre);


--
-- Name: personas uknnr7w7h44crpy3wdqmk1724hp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas
    ADD CONSTRAINT uknnr7w7h44crpy3wdqmk1724hp UNIQUE (dni);


--
-- Name: cupones ukpp15mnldgaun94tk2cy054335; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupones
    ADD CONSTRAINT ukpp15mnldgaun94tk2cy054335 UNIQUE (codigo);


--
-- Name: orden_delivery_info ukqr1mfikwv8u0eud5938gg8a8e; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_delivery_info
    ADD CONSTRAINT ukqr1mfikwv8u0eud5938gg8a8e UNIQUE (orden_id);


--
-- Name: vehiculos vehiculos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehiculos
    ADD CONSTRAINT vehiculos_pkey PRIMARY KEY (id);


--
-- Name: whatsapp_sesiones whatsapp_sesiones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.whatsapp_sesiones
    ADD CONSTRAINT whatsapp_sesiones_pkey PRIMARY KEY (id);


--
-- Name: orden_delivery_info fk15bx92n465xc4bpy6764vvvje; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_delivery_info
    ADD CONSTRAINT fk15bx92n465xc4bpy6764vvvje FOREIGN KEY (transportista_id) REFERENCES public.transportistas(persona_id);


--
-- Name: promociones fk2m17lc8l4nv2r0wfe46fio5mp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promociones
    ADD CONSTRAINT fk2m17lc8l4nv2r0wfe46fio5mp FOREIGN KEY (insumo_extra_id) REFERENCES public.insumos(id);


--
-- Name: rol_permisos fk3brv6p1mw68brbj5gq8xtq8el; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol_permisos
    ADD CONSTRAINT fk3brv6p1mw68brbj5gq8xtq8el FOREIGN KEY (rol_id) REFERENCES public.roles(id);


--
-- Name: platillos fk3dpf83n5ld5wjb2qh6p7rjpcu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platillos
    ADD CONSTRAINT fk3dpf83n5ld5wjb2qh6p7rjpcu FOREIGN KEY (categoria_id) REFERENCES public.categorias_platillo(id);


--
-- Name: controles_insumo fk51rmcrnkk3e9e9w2t4ba4c8af; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.controles_insumo
    ADD CONSTRAINT fk51rmcrnkk3e9e9w2t4ba4c8af FOREIGN KEY (insumo_id) REFERENCES public.insumos(id);


--
-- Name: transportistas fk73yhggp4i5mxrm75k0m839vrd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transportistas
    ADD CONSTRAINT fk73yhggp4i5mxrm75k0m839vrd FOREIGN KEY (persona_id) REFERENCES public.personas(id);


--
-- Name: trabajadores fk74dlm3nyrvv5ubufyb4por113; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trabajadores
    ADD CONSTRAINT fk74dlm3nyrvv5ubufyb4por113 FOREIGN KEY (persona_id) REFERENCES public.personas(id);


--
-- Name: orden_detalle_complementos fk89qtlhuxhi0a1hrbpb56ujg1r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_detalle_complementos
    ADD CONSTRAINT fk89qtlhuxhi0a1hrbpb56ujg1r FOREIGN KEY (complemento_id) REFERENCES public.complementos_platillo(id);


--
-- Name: calificaciones_feedback fk8bdonmh61n5ik6mks22nmo7he; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificaciones_feedback
    ADD CONSTRAINT fk8bdonmh61n5ik6mks22nmo7he FOREIGN KEY (orden_id) REFERENCES public.ordenes(id);


--
-- Name: rol_permisos fk9a92613h451aryhufw6j7m4yd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol_permisos
    ADD CONSTRAINT fk9a92613h451aryhufw6j7m4yd FOREIGN KEY (permiso_id) REFERENCES public.permisos(id);


--
-- Name: orden_detalle_complementos fk9o3qvjh5wstk77er57ea1f7km; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_detalle_complementos
    ADD CONSTRAINT fk9o3qvjh5wstk77er57ea1f7km FOREIGN KEY (orden_detalle_id) REFERENCES public.orden_detalles(id);


--
-- Name: complementos_platillo fkcn36tsol527g896bj569c33ma; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complementos_platillo
    ADD CONSTRAINT fkcn36tsol527g896bj569c33ma FOREIGN KEY (insumo_asociado_id) REFERENCES public.insumos(id);


--
-- Name: sesiones_bot fkd0epa5griua9vmsh56cstlkdu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesiones_bot
    ADD CONSTRAINT fkd0epa5griua9vmsh56cstlkdu FOREIGN KEY (cliente_id) REFERENCES public.clientes(persona_id);


--
-- Name: vehiculos fkd6giq700i9gm4db0etmru5xid; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehiculos
    ADD CONSTRAINT fkd6giq700i9gm4db0etmru5xid FOREIGN KEY (transportista_id) REFERENCES public.transportistas(persona_id);


--
-- Name: cliente_empresas fke726bib17chuib1u7vo213m76; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente_empresas
    ADD CONSTRAINT fke726bib17chuib1u7vo213m76 FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: trabajadores fkf6waf5cmxntf1bhoeruvpmsfs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trabajadores
    ADD CONSTRAINT fkf6waf5cmxntf1bhoeruvpmsfs FOREIGN KEY (cargo_id) REFERENCES public.cargos(id);


--
-- Name: calificaciones_feedback fkfswmipcr7l9dko1tp1m8qk2o8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificaciones_feedback
    ADD CONSTRAINT fkfswmipcr7l9dko1tp1m8qk2o8 FOREIGN KEY (cliente_id) REFERENCES public.clientes(persona_id);


--
-- Name: pagos fkgwc09q159u2vka6huvllyf6jy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT fkgwc09q159u2vka6huvllyf6jy FOREIGN KEY (orden_id) REFERENCES public.ordenes(id);


--
-- Name: orden_delivery_info fkhqauafchtl2w5n0glbm27qitm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_delivery_info
    ADD CONSTRAINT fkhqauafchtl2w5n0glbm27qitm FOREIGN KEY (vehiculo_id) REFERENCES public.vehiculos(id);


--
-- Name: cargo_roles fkii5nja9044ps4dp9ahf8mrib8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cargo_roles
    ADD CONSTRAINT fkii5nja9044ps4dp9ahf8mrib8 FOREIGN KEY (cargo_id) REFERENCES public.cargos(id);


--
-- Name: ordenes fkivblb1hhhhk7oajou6bryt7ef; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordenes
    ADD CONSTRAINT fkivblb1hhhhk7oajou6bryt7ef FOREIGN KEY (promocion_id) REFERENCES public.promociones(id);


--
-- Name: insumos_platillo fklgiipdgqia45v5etp7f6ei01u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumos_platillo
    ADD CONSTRAINT fklgiipdgqia45v5etp7f6ei01u FOREIGN KEY (platillo_id) REFERENCES public.platillos(id);


--
-- Name: orden_detalles fklkdlqe3cu64h1n96mjvah9nhk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_detalles
    ADD CONSTRAINT fklkdlqe3cu64h1n96mjvah9nhk FOREIGN KEY (platillo_id) REFERENCES public.platillos(id);


--
-- Name: ordenes fkmftalwehlpu8ntrikv005falt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordenes
    ADD CONSTRAINT fkmftalwehlpu8ntrikv005falt FOREIGN KEY (cliente_id) REFERENCES public.clientes(persona_id);


--
-- Name: whatsapp_sesiones fkmt2ni1gqfq9nj57ki9a1t60rn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.whatsapp_sesiones
    ADD CONSTRAINT fkmt2ni1gqfq9nj57ki9a1t60rn FOREIGN KEY (cliente_id) REFERENCES public.clientes(persona_id);


--
-- Name: insumos_platillo fko0pmftyjjiolej50ky5c8f3rc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumos_platillo
    ADD CONSTRAINT fko0pmftyjjiolej50ky5c8f3rc FOREIGN KEY (insumo_id) REFERENCES public.insumos(id);


--
-- Name: cupones fkop7n0qy0x5nf7v5xyknikmn3w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupones
    ADD CONSTRAINT fkop7n0qy0x5nf7v5xyknikmn3w FOREIGN KEY (cliente_id) REFERENCES public.clientes(persona_id);


--
-- Name: orden_detalles fkq8bl569i57pt5l3wuuwbi28yi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_detalles
    ADD CONSTRAINT fkq8bl569i57pt5l3wuuwbi28yi FOREIGN KEY (orden_id) REFERENCES public.ordenes(id);


--
-- Name: clientes fkqqdwv2x70kik01nxcgkxvh8ue; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT fkqqdwv2x70kik01nxcgkxvh8ue FOREIGN KEY (persona_id) REFERENCES public.personas(id);


--
-- Name: orden_delivery_info fkrca9scw99hx9s3bnw9ielqr6o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orden_delivery_info
    ADD CONSTRAINT fkrca9scw99hx9s3bnw9ielqr6o FOREIGN KEY (orden_id) REFERENCES public.ordenes(id);


--
-- Name: cargo_roles fks1frcyxvdiv6fhl8sxitdy6nc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cargo_roles
    ADD CONSTRAINT fks1frcyxvdiv6fhl8sxitdy6nc FOREIGN KEY (rol_id) REFERENCES public.roles(id);


--
-- Name: ordenes fks2tjpkbsk1cbp2gql0wndhwen; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordenes
    ADD CONSTRAINT fks2tjpkbsk1cbp2gql0wndhwen FOREIGN KEY (mesa_id) REFERENCES public.mesas(id);


--
-- Name: cliente_empresas fkto1u8nafws81trw41p2fe2og3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente_empresas
    ADD CONSTRAINT fkto1u8nafws81trw41p2fe2og3 FOREIGN KEY (persona_id) REFERENCES public.personas(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 71PJlu1V74g1RoT8Ig5kMfCfedvgXAjleOQJpzOmxERFZk3NDAnLhuxBQ04ChdI

